apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeForwardingRule
metadata:
  name: node-app-forwarding-rule
spec:
  target:
    targetHTTPProxyRef:
      name: node-app-target-proxy
  portRange: "80"
  ipProtocol: "TCP"
  ipVersion: "IPV4"
  location: global
