apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computeinstance-dep1-cloudmachine
spec:
  description: a sample encrypted, blank disk
  physicalBlockSizeBytes: 4096
  size: 1
  type: pd-ssd
  location: us-west1-a
  diskEncryptionKey:
    rawKey:
      valueFrom:
        secretKeyRef:
          name: computeinstance-dep-cloudmachine
          key: diskEncryptionKey
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computeinstance-dep2-cloudmachine
spec:
  size: 1
  type: pd-ssd
  location: us-west1-a