apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: computeinstance-dep-cloudmachine
spec:
  networkRef:
    name: computeinstance-dep-cloudmachine
  ipCidrRange: 10.2.0.0/16
  region: us-west1
  secondaryIpRange:
    - rangeName: cloudrange
      ipCidrRange: 10.3.16.0/20