apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendBucket
metadata:
  name: computebackendbucket-sample-cdnenabled
  labels:
    label-one: "value-one"
spec:
  bucketRef:
    name: computebackendbucket-dep-cdnenabled
  description: contains a reference to a bucket for use with HTTP(S) load-balancing and integrated CDN, caching on endpoints for only 1/10th the default time
  enableCdn: true
  cdnPolicy:
    signedUrlCacheMaxAgeSec: 360