apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "false"
  labels:
    label-one: "value-one"
  name: containernodepool-dep
spec:
  location: us-east1-c
  initialNodeCount: 1
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  masterAuth:
    username: "user"
    password:
      valueFrom:
        secretKeyRef:
          name: containernodepool-dep
          key: password
    clientCertificateConfig:
      issueClientCertificate: false
