apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: computebackendservice-sample-regional
spec:
  backend:
    - group:
        instanceGroupRef:
          name: computebackendservice-dep-regional
  healthChecks:
    - healthCheckRef:
        name: computebackendservice-dep-regional
  location: us-central1
  loadBalancingScheme: INTERNAL
