apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceGroup
metadata:
  name: computebackendservice-dep-regional
spec:
  instances:
    - name: computebackendservice-dep-regional
  namedPort:
    - name: http
      port: 8080
    - name: https
      port: 8443
  networkRef:
    name: computebackendservice-dep-regional
  zone: us-central1-a
