apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeResourcePolicy
metadata:
  name: computeresourcepolicy-sample-dailyschedule
spec:
  region: us-central1
  snapshotSchedulePolicy:
    schedule:
      dailySchedule:
        daysInCycle: 1
        startTime: "00:00"
    retentionPolicy:
      maxRetentionDays: 8
      onSourceDiskDelete: KEEP_AUTO_SNAPSHOTS
    snapshotProperties:
      storageLocations:
      - us-central1
      guestFlush: true
      labels:
        autodeleted: "false"
        interval: "daily"