apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: instancetemplate-dep
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-west1
  description: a sample subnetwork
  enableFlowLogs: true
  privateIpGoogleAccess: false
  networkRef:
    name: instancetemplate-dep
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
