apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: sqluser-sample
spec:
  instanceRef:
    name: sqluser-dep
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: sqluser-dep
        key: password
