apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computesnapshot-dep
spec:
  location: us-west1-c
  diskEncryptionKey:
    rawKey:
      valueFrom:
        secretKeyRef:
          name: computesnapshot-dep
          key: sourceDiskEncryptionKey