apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSSLCertificate
metadata:
  name: computetargethttpsproxy-dep
spec:
  location: global
  certificate:
    valueFrom:
      secretKeyRef:
        name: computetargethttpsproxy-dep
        key: certificate
  privateKey:
    valueFrom:
      secretKeyRef:
        name: computetargethttpsproxy-dep
        key: privateKey
