apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: sql-sa-policy
spec:
  member: serviceAccount:sql-wp-sa@[PROJECT_ID].iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    kind: Project 
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: [PROJECT_ID]
