apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeImage
metadata:
  name: computeimage-sample-fromurlraw
  labels:
    image-type: stemcell
spec:
  description: A sample image created from URL to a raw TAR disk image
  family: ubuntu-custom
  licenses: ["https://ubuntu.com/licensing"]
  rawDisk:
    source: "https://storage.googleapis.com/bosh-cpi-artifacts/bosh-stemcell-3262.7-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz"
    containerType: "TAR"
    sha1: d0646960085a472899db41f6065e6b627919b3a9