apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computedisk-sample-zonal
  labels:
    label-one: "value-one"
spec:
  description: a sample encrypted, blank disk
  diskEncryptionKey:
    rawKey:
      valueFrom:
        secretKeyRef:
          name: computedisk-dep-zonal
          key: sharedSecret
  physicalBlockSizeBytes: 4096
  size: 1
  type: pd-ssd
  location: us-west1-c