apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  name: computebackendservice-dep-global
spec:
  checkIntervalSec: 10
  httpHealthCheck:
    port: 80
  location: global
