apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: sql-wp-sa-project-policymember
spec:
  member: serviceAccount:sql-wp-sa@project-id.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    kind: Project
    name: project-id
