apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./gcp-sql-db.yaml
- ./gcp-sql-instance.yaml
- ./gcp-sql-policy-member.yaml
- ./gcp-sql-service-account.yaml
- ./gcp-sql-user.yaml
- ./gcp-wi-policy.yaml
- ./k8s-external-load-balancer.yaml
- ./k8s-service-account.yaml
- ./k8s-service.yaml
- ./k8s-sql-db-credentials.yaml
- ./k8s-stateful-set.yaml
