apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: dnsrecordset-sample-ns
spec:
  name: "example.com."
  type: "NS"
  ttl: 300
  managedZoneRef:
    name: dnsrecordset-dep-ns
  rrdatas:
  - "ns-cloud-a1.googledomains.com."
  - "ns-cloud-a2.googledomains.com."
  - "ns-cloud-a3.googledomains.com."
  - "ns-cloud-a4.googledomains.com."