apiVersion: v1
kind: ServiceAccount
metadata:
  name: iampolicy-dep-workloadidentity
  annotations:
    # replace ${PROJECT_ID?} with your project name
    iam.gke.io/gcp-service-account: iampolicy-dep-workloadidentity@${PROJECT_ID?}.iam.gserviceaccount.com
