apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: bucket-policy-team-a
  namespace: team-a
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1alpha2
    kind: StorageBucket
    name: [PROJECT_ID]-team-a-bucket
    namespace: team-a
  bindings:
    - role: roles/storage.admin
      members:
        - serviceAccount:sa-bucket-team-a@[PROJECT_ID]-team-a.iam.gserviceaccount.com
