apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: computerouter-sample
spec:
  networkRef:
    name: computerouter-dep
  description: example router description
  region: us-west1
  bgp:
    asn: 64514
    advertiseMode: CUSTOM
    advertisedGroups:
      - ALL_SUBNETS
    advertisedIpRanges:
      - range: "1.2.3.4"
