apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: computeinstance-dep-networkworker
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-west1
  description: a sample subnetwork
  privateIpGoogleAccess: false
  networkRef:
    name: computeinstance-dep-networkworker
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
