apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  name: computehealthcheck-sample-regional
spec:
  checkIntervalSec: 10
  httpHealthCheck:
    port: 80
  location: us-central1
