apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: computetargetsslproxy-dep
spec:
  healthChecks:
    - healthCheckRef:
        name: computetargetsslproxy-dep
  location: global
  protocol: SSL