apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetSSLProxy
metadata:
  name: computetargetsslproxy-sample
spec:
  description: "A sample SSL proxy configured with a default SSL policy."
  backendServiceRef:
    name: computetargetsslproxy-dep
  sslCertificates:
    - name: computetargetsslproxy-dep
  sslPolicyRef:
    name: computetargetsslproxy-dep