apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: cnrm-bookstore-pubsub-policy
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: cnrm-topic
  bindings:
    - role: roles/editor
      members:
        - serviceAccount:cnrm-bookstore-frontend@[PROJECT_ID].iam.gserviceaccount.com