apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeResourcePolicy
metadata:
  name: computeresourcepolicy-sample-hourlyschedule
spec:
  region: us-central1
  snapshotSchedulePolicy:
    schedule:
      hourlySchedule:
        hoursInCycle: 4
        startTime: "13:00"
    retentionPolicy:
      maxRetentionDays: 2
      onSourceDiskDelete: APPLY_RETENTION_POLICY
    snapshotProperties:
      labels:
        autodeleted: "true"
        interval: "hourly"