apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: gcr-bucket-policy
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: artifacts.[PROJECT_ID].appspot.com
  bindings:
    - role: roles/storage.objectViewer
      members:
        - serviceAccount:gcr-sa@[PROJECT_ID].iam.gserviceaccount.com
