apiVersion: v1
kind: Service
metadata:
  name: node-app-backend
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    anthos.cft.dev/autoneg: '{"name":"node-app-backend-service", "max_rate_per_endpoint":100}'
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
  - port: 80
    targetPort: 8080
