apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  name: computeinstance-dep-fromtemplate
spec:
  machineType: n1-standard-1
  region: us-west1
  disk:
    - sourceDiskRef:
        name: computeinstance-dep-fromtemplate
      boot: true
  networkInterface:
    - networkRef:
        name: computeinstance-dep-fromtemplate
