apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
patchesJson6902:
  - target:
      group: iam.cnrm.cloud.google.com
      version: v1alpha1
      kind: IAMPolicyMember
      name: sql-wp-sa-project-policymember
    path: gcp-sql-policy-member-patch.yaml
  - target:
      group: iam.cnrm.cloud.google.com
      version: v1alpha1
      kind: IAMPolicy
      name: sql-wp-sa-wi-policy
    path: gcp-wi-policy-patch.yaml
  - target:
      version: v1
      kind: ServiceAccount
      name: sql-wp-ksa-wi
    path: k8s-service-account-patch.yaml
  - target:
      version: v1
      kind: Secret
      name: wordpress-cloudsql-db-credentials
    path: k8s-sql-db-credentials-patch.yaml

